name: approval_tests_flutter
description: Approval Tests implementation in Dart (Flutter). Inspired by ApprovalTests.
version: 1.1.6
repository: https://github.com/approvals/ApprovalTests.Flutter
homepage: https://github.com/approvals/ApprovalTests.Flutter.git
issue_tracker: https://github.com/approvals/ApprovalTests.Flutter/issues
# publish_to: 'none'

topics:
  - test
  - approval
  - approvals
  - tests
  - approval-tests

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  #   meta: ^1.14.0
  # test_api: ^0.7.3

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  approval_tests: ^1.1.6
  test: ^1.25.2
  test_api: ^0.7.3
  analyzer: ^6.11.0

dev_dependencies:
  sizzle_lints: ^2.1.5
